Pengenalan mysql dan ddl
wrideveloper/miniclass-web pull request #117
Opened 2022-01-29 09:14 UTC by DikhiAchmad

2022-02-05 12:05 UTC, wridev commented on draft/database/ddl.md
> +## 4. Penjelasan Detail tentang Tipe Data dan Perintah DDL
Hehe abis 2 kok langsung 4

2022-02-05 12:09 UTC, nargyanti commented on draft/database/ddl.md
> +DDL(Data Definition Language) merupakan salah satu dari bentuk SQL yang bisa digunakan untuk membuat database, tabel, struktur tabel, merubah struktur database, menghapus tabel, menghapus database se
Mungkin dibikin point aja biar gak pusing bacanya

2022-02-05 12:09 UTC, nargyanti commented on draft/database/ddl.md
> +DDL(Data Definition Language) merupakan salah satu dari bentuk SQL yang bisa digunakan untuk membuat database, tabel, struktur tabel, merubah struktur database, menghapus tabel, menghapus database se
Yang perintah dasar kek create alter drop itu mungkin dihapus aja soalnya udah dijelasin di bawah

2022-02-05 12:10 UTC, nargyanti commented on draft/database/ddl.md
> +## 4. Penjelasan Detail tentang Tipe Data dan Perintah DDL
Habis 2 kok langsung 4? hehe

2022-02-05 12:22 UTC, nargyanti requested changes
Minta tolong disolve ya revisinya :D

2022-02-05 12:22 UTC, nargyanti commented on draft/database/ddl.md
> +![database](erd.png)
Fotonya nda keluar

2022-02-05 12:22 UTC, nargyanti commented on draft/database/mysql.md
> +Tentunya website membutuhkan database server untuk menampung berbagai jenis informasi. Situs web memerlukan berbagai jenis data  seperti data pribadi dan sebagainya. MySQL adalah  sistem manajemen ba
Mungkin ditambahkan semacem pernyataan bahwa tempat ngelola database itu banyak, kayak MySQL, MongoDB, dll.

2022-02-05 12:22 UTC, nargyanti commented on draft/database/mysql.md
> +## 3. Install XAMPP
Ditambahkan penjelasan apa itu XAMPP dan kenapa pakai XAMPP dibanding yang lain

2022-02-05 12:22 UTC, nargyanti commented on draft/database/mysql.md
> +## 5. Menjalankan Localhost MYSQL
Kok langsung 5? Harusnya 4, hehe

2022-02-09 17:43 UTC, nargyanti approved these changes
Approved, tapi dengan catatan tadi aku benerin huruf kapitalnya

2022-02-09 17:44 UTC, merged