Silabus Cookies
wrideveloper/miniclass-web pull request #120
Opened 2022-01-30 07:52 UTC by dewangga12

2022-02-05 12:47 UTC, nargyanti requested changes

2022-02-05 12:47 UTC, nargyanti commented on draft/PHP/cookies.md
> +    Cookies berguna untuk memudahkan pengguna, seperti "mengingat" user setiap kali mengunjungi website yang sama.
Jangan dibikin ada indentnya, soalnya jadi kescroll textnya

2022-02-05 12:47 UTC, nargyanti commented on draft/PHP/cookies.md
> +    Seringkali saat client melakukan suatu aktivitas yang berhubungan dengan mengisi data (form), client terkadang malas untuk mengetik kembali data atau informasi yang sudah pernah user ketikkan seb
Jangan dibikin ada indentnya, soalnya jadi kescroll textnya

2022-02-05 12:47 UTC, nargyanti commented on draft/PHP/cookies.md
> +    A. Untuk membuat cookies pada PHP,  fungsi 'setcookie()'
Jangan dibikin ada indentnya, soalnya jadi kemasukan ke kkolom quotenya

Lebih bagus dikasih heading 3 (###)

2022-02-05 12:47 UTC, nargyanti commented on draft/PHP/cookies.md
> +    B. Setelah cookie dibuat, selanjutnya kita dapat mengambil cookie yang telah dibuat dengan variabel cookie '$_COOKIE'
Lebih bagus dikasih heading 3 (###)

2022-02-05 12:47 UTC, nargyanti commented on draft/PHP/cookies.md
> +    C. Contoh Pembuatan Cookie
Lebih bagus dikasih heading 3 (###)

2022-02-05 12:47 UTC, nargyanti commented on draft/PHP/cookies.md
> +    A. Untuk menghapus cookies sangat mudah yaitu dengan mengubah expire nya yang semula time()+3600 menjadi time()-3600
Lebih bagus dikasih heading 3 (###)

2022-02-05 12:47 UTC, nargyanti commented on draft/PHP/cookies.md
> +    B. Contoh Menghapus Cookies
Lebih bagus dikasih heading 3 (###)

2022-02-07 06:48 UTC, nargyanti requested changes

2022-02-07 06:48 UTC, nargyanti commented on draft/PHP/cookies.md
> +    expire adalah jangka waktu cookies akan disimpan di dalam komputer
Ini paragrafnya juga masih masuk ke dalem, kayaknya sekalian dikiriin semua biar bisa rapi

2022-02-07 06:48 UTC, nargyanti commented on draft/PHP/cookies.md
> +    ```
Ini paragrafnya juga masih masuk ke dalem, kayaknya sekalian dikiriin semua biar bisa rapi

2022-02-07 06:48 UTC, nargyanti commented on draft/PHP/cookies.md
> +        4.Jalankan file cookiesCall.php pada localhost
Ini paragrafnya juga masih masuk ke dalem, kayaknya sekalian dikiriin semua biar bisa rapi

2022-02-07 06:48 UTC, nargyanti commented on draft/PHP/cookies.md
> +### C. ontoh Pembuatan Cookie
Typo :D

2022-02-07 06:48 UTC, nargyanti commented on draft/PHP/cookies.md
> +        3. Lalu jalankan file cookiesCall.php pada localhost untuk melihat hasilnya
Ini paragrafnya juga masih masuk ke dalem, kayaknya sekalian dikiriin semua biar bisa rapi

2022-02-07 06:50 UTC, dewangga12 commented on draft/PHP/cookies.md
> +        3. Lalu jalankan file cookiesCall.php pada localhost untuk melihat hasilnya
berarti list angka nya full kiri ya mbak?

2022-02-07 07:15 UTC, nargyanti approved these changes

2022-02-07 07:16 UTC, merged