Anatomi css
wrideveloper/miniclass-web pull request #52
Opened 2020-03-10 13:26 UTC by zero0dayali

mohon di review..

2020-03-11 06:14 UTC, mnindrazaka requested changes
ini masih pake struktur yang lama, pake struktur materi yang baru, gak perlu ngikutin yang lama. harusnya ceritain problem dulu, baru penjelasan css nya.

kita tetap berpatok pada guideline ini ya
https://github.com/wrideveloper/miniclass-guideline

2020-03-11 06:28 UTC, mnindrazaka requested changes

2020-03-11 06:28 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
> + CSS adalah singkatan dari Cascading StyleSheet yang merupakan bahasa `style sheet` yang tujuan utama nya adalah untuk membantu mengatur keindahan di aplikasi web yang ditulis dengan HTML. Apabila HT
ceritain problemnya dulu, baru penjelasan css nya. sebisa mungkin ikut struktur yang ada di guideline

2020-03-11 06:28 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
> +selector { property: value; }
struktur nya ini perlu dijelasin, `selector` itu apa, `property` itu apa, `value` itu apa

2020-03-11 06:28 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
> +``` -->
termasuk ini, contoh implementasi itu bisa dijelaskan maksudnya apa, misalnya : 
disana kita akan melakukan styling pada tag `h1`, dimana kita akan merubah `property` `color` menjadi berwarna merah

2020-03-11 06:28 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
> +Memasukkan file css eksternal ke dalam html maksudnya adalah file html di pisah dengan file css , lalu kita hubungkan dengan cara seperti dibawah ini ,di bawah ini saya hubungkan html saya dengan `my
untuk mulai menjelaskan eksternal css ini, bisa mulai dari problemnya dulu, misalnya dijelaskan kalau kita menulis css didalam html menggunakan tag `<style />`, maka apabila styling yang kita lakukan banyak, akan membuat file html kita penuh, sehingga struktur dan stylingnya perlu dipisah pada file yang berbeda.

2020-03-11 06:28 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
> +Menulis css langsung ke tag tertentu pada html di bawah ini saya mencontohkan menggunakan `h1` dan menambahkan css di dalamnya seperti `color` dan `text-align` .
Setelah aku pikir2. kyknya `inline css` ini lebih enak kalau dijelasin di poin pertama, jadi jelasinnya bisa nyambung satu sama lain. nanti bakal kyk gini : 

1. inline css : nulis langsung di tag yang mau di styling, cepet, tapi struktur html jadi kotor dan susah dibaca.

2. pake tag style : struktur html dan styling sudah mulai dipisah, sehingga bisa baca struktur html dengan lebih enak. tapi kalau stylingnya banyak, baris file htmlnya jadi banyak.

3. eksternal css : struktur html dan styling dipisah file, jadi bisa lebih fokus buat ngedit struktur (di file html) dan ngedit styling (di file css)

2020-03-11 06:28 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
> +Selector merupakan suatu cara dimana kita ingin mengelompokan kode-kode didalam CSS dan juga merupakan aturan yang digunakan untuk memisahkan kode-kode dengan target berbeda. Selector digunakan untuk
selector ini kyknya ga perlu dijelasin lagi disini, harusnya udah dijelasin di struktur css

2020-03-11 06:28 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
> +Property merupakan suatu jenis style CSS yang berfungsi memberikan style pada selector yang telah ditentukan. Property pada CSS sangat banyak sekali. Misalnya property yang biasa kita temukan adalah
termasuk property ini, gak perlu dijelasin disini, harusnya sudah di struktur css

2020-03-11 06:28 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
> +![alt text](img/anatomi2.jpg)
yang ini juga ga perlu sih, udah dijelasin di struktur css juga

2020-03-11 06:28 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
>  }
termasuk komentar ini, kira2 perlu dijelasin gak ya ?

2020-03-11 07:32 UTC, zero0dayali commented on dasar/css/pengenalan-css.md
> + CSS adalah singkatan dari Cascading StyleSheet yang merupakan bahasa `style sheet` yang tujuan utama nya adalah untuk membantu mengatur keindahan di aplikasi web yang ditulis dengan HTML. Apabila HT
okok ,aku tambahin mas
terimaksih review nya

2020-03-11 07:33 UTC, zero0dayali commented on dasar/css/pengenalan-css.md
> +selector { property: value; }
sebenernya kalo aku ngerasa ini sudah cukup seperti ini karena di atas sudah ada contoh gambar anatomi dari css

2020-03-11 07:34 UTC, zero0dayali commented on dasar/css/pengenalan-css.md
> +``` -->
okok siap aku jelasin 
terimaksih review nya

2020-03-11 07:34 UTC, zero0dayali commented on dasar/css/pengenalan-css.md
> +Memasukkan file css eksternal ke dalam html maksudnya adalah file html di pisah dengan file css , lalu kita hubungkan dengan cara seperti dibawah ini ,di bawah ini saya hubungkan html saya dengan `my
okok aku tambahin wkwkwk

2020-03-11 07:35 UTC, zero0dayali commented on dasar/css/pengenalan-css.md
> +Selector merupakan suatu cara dimana kita ingin mengelompokan kode-kode didalam CSS dan juga merupakan aturan yang digunakan untuk memisahkan kode-kode dengan target berbeda. Selector digunakan untuk
okok siap

2020-03-11 07:36 UTC, zero0dayali commented on dasar/css/pengenalan-css.md
>  }
perlu

2020-03-11 07:38 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
> +selector { property: value; }
bener, udah ada gambarnya, tapi dia cuma nunjukin yang mana selector, yang property, dan yang mana value. Tapi gak ngejelasin mereka apa, pembaca yang baru kenal banget sama css bakal butuh penjelasan lebih lanjut.

2020-03-11 10:43 UTC, mnindrazaka requested changes
Dari segi struktur udah oke, tinggal gimana caranya agar penjelasannya dibuat lebih sederhana supaya mudah dipahami oleh pembaca yang baru belajar. Di beberapa bagian nanti bakal aku bantu jelasin.

2020-03-11 10:43 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
> +**Selector** merupakan suatu cara dimana kita ingin mengelompokan kode-kode didalam CSS dan juga merupakan aturan yang digunakan untuk memisahkan kode-kode dengan target berbeda. Selector digunakan u
Selector ini sebenernya buat memilih elemen html yang ingin kita terapkan styling. Cara menjelaskan perlu dibuat lebih sederhana lagi, supaya mudah dipahami

2020-03-11 10:43 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
>  ```
Ini nanti butuh penjelasan lagi kyknya

2020-03-11 10:43 UTC, mnindrazaka commented on dasar/css/pengenalan-css.md
> +**Property** merupakan suatu jenis style CSS yang berfungsi memberikan style pada selector yang telah ditentukan. Property pada CSS sangat banyak sekali. Misalnya property yang biasa kita temukan ada
Penjelasannya sudah benar, tinggal dikembangkan lagi supaya lebih sederhana, nanti aku bantu benerin kata2nya biar lebih mudah dipahami

2020-03-15 10:31 UTC, mnindrazaka approved these changes
LGTM

2020-03-15 10:31 UTC, merged