update file readme dan menambahkan gambar
wrideveloper/miniclass-web pull request #63
Opened 2020-03-21 15:25 UTC by naufalyukafi

2020-03-23 02:53 UTC, mnindrazaka requested changes

2020-03-23 02:53 UTC, mnindrazaka commented on dasar/html/list.md
> +  Pada pembuatan website, biasanya kita butuh menampilkan data dalam bentuk list untuk mempermudah pembacaan. Namun, pada HTML kita tidak bisa langsung membuat list menggunakan text. contohnya sepert
kayaknya ini lebih oke kalo ditambahin contoh - contoh penggunaan list pada website, biar pembacanya lebih kebayang

```suggestion
Pada pembuatan website, biasanya kita butuh menampilkan data dalam bentuk list untuk mempermudah pembacaan. Misalnya pada website media sosial, kita dapat menampilkan daftar user yang sedang online menggunakan list. Namun, pada HTML kita tidak bisa langsung membuat list menggunakan text. contohnya seperti berikut :
```

2020-03-23 02:53 UTC, mnindrazaka commented on dasar/html/list.md
> +  kode di atas jika di tampilkan di web browser maka hasilnya akan seperti berikut:
ada typo dikit

```suggestion
  kode di atas jika ditampilkan di web browser maka hasilnya akan seperti berikut :
```

2020-03-23 02:53 UTC, mnindrazaka commented on dasar/html/list.md
> +  Oleh karena itu dengan adanya permasalahan di atas maka kita bisa menggunakan kombinasi dari tag ```<ol/> dan <ul/>```.
kalo code nya cuma satu baris, bisa pake single quote aja ` 

```suggestion
Oleh karena itu dengan adanya permasalahan di atas maka kita bisa menggunakan kombinasi dari tag `<ol/>`, `<ul/>` dan `<li />`.
```

2020-03-23 02:53 UTC, mnindrazaka commented on dasar/html/list.md
> +## 3. Detail Materi
ini judulnya bisa langsung diubah aja

```suggestion
## 3. Penjelasan List HTML
```

2020-03-23 02:53 UTC, mnindrazaka commented on dasar/html/list.md
> +## 4. Praktek!
yang ini judulnya tetep contoh kasus aja sementara, biar seragam dulu

```suggestion
## 4. Contoh Kasus
```

2020-03-23 02:53 UTC, mnindrazaka commented on dasar/html/list.md
> +  ![Latihan list](latihanList.jpg)
yang bagian ini kyknya gak oke kalo langsung latihan, butuh contoh kasus dulu. Jadi untuk minggu2 ini fokus sampai contoh kasus dulu. Ntar kalau sudah rapi semua baru ditambahi latihan praktek

Soalnya kalo gak ada step by step contoh kasus, nanti pas miniclass fasilitator masih harus mendemokan contoh kasusnya, gak solving the problem silabus ini ntar

2020-03-23 03:11 UTC, naufalyukafi commented
Berarti saya harus buat contoh kasus baru di bagian akhir artikel yah mas?

2020-04-01 06:39 UTC, mnindrazaka commented
@naufalyukafi any update ?

2020-04-01 20:41 UTC, naufalyukafi commented
Siap maas mohon maaf kemarin saya di sibukkan dengan desain(kalo pulkam
selalu di suruh desain sama kakak saya mas hehe)

Pada tanggal Rab, 1 Apr 2020 pukul 13.39 M Nindra Zaka <
notifications@github.com> menulis:

> @naufalyukafi <https://github.com/naufalyukafi> any update ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wrideveloper/miniclass-web/pull/63#issuecomment-607064418>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANQL6QK7QRWX64W467BJCV3RKLORFANCNFSM4LQ6K72Q>
> .
>

2020-04-01 23:18 UTC, mnindrazaka approved these changes
LGTM

2020-04-01 23:18 UTC, merged