menambah deskripsi permasalahan, contoh source code dan penjelasan
wrideveloper/miniclass-web pull request #64
Opened 2020-03-22 09:28 UTC by fransiskalidya

mas, tolong di review

2020-03-23 03:13 UTC, mnindrazaka requested changes
Ada beberapa comment.

Sama ini belum ada point contoh kasusnya ya ? perlu ditambahin sih

2020-03-23 03:13 UTC, mnindrazaka commented on dasar/html/link.md
> +saat membuat sebuah website, kita membutuhkan penghubung menuju file html lain atau website lain.
ini menurutku perlu disebutin contoh penggunaan link pada website

```suggestion
Saat membuat sebuah website, terkadang kita butuh membuat link untuk menuju url lain. misalnya saat membuat menu navigasi atau membuat link unduh file. Pada topik ini akan dibahas bagaimana cara membuat link menggunakan HTML
```

2020-03-23 03:13 UTC, mnindrazaka commented on dasar/html/link.md
> +pada baris ketiga, tag `a` yang tidak diikuti dengan `href` tidak dapat memuat link yang dapat diklik dan tampilannya akan berupa tulisan biasa. Sedangkan pada baris keempat tidak akan memunculkan tu
bagian ini perlu dipecah menjadi dua sub point

3.1. Membuat link menuju URL lain
[penjelasan]
[code]

3.2. Membuat link menuju file HTML lain
[penjelasan]
[code]

2020-03-23 03:35 UTC, fransiskalidya commented on dasar/html/link.md
> +pada baris ketiga, tag `a` yang tidak diikuti dengan `href` tidak dapat memuat link yang dapat diklik dan tampilannya akan berupa tulisan biasa. Sedangkan pada baris keempat tidak akan memunculkan tu
Apa yang ini dijadiin studi kasus nya mas? Kemaren mas aka kan kasih note kalau studi kasusnya langkah langkah?

2020-03-31 22:35 UTC, mnindrazaka approved these changes
LGTM

2020-03-31 22:36 UTC, merged

2021-02-23 18:24 UTC, sidiqgunawan approved these changes
[```


```