Mengubah struktur materi text fomatting CSS berdasarkan guideline
wrideveloper/miniclass-web pull request #71
Opened 2020-03-28 09:26 UTC by nargyanti

2020-03-30 21:19 UTC, mnindrazaka requested changes

2020-03-30 21:19 UTC, mnindrazaka commented on dasar/css/text-formatting.md
> +Karena referensi tidak termasuk ke dalam paragraf di dalam artikel, kita harus membuat tampilan paragraf referensi tampak berbeda dengan paragraf artikel. Hal ini bertujuan agar pengunjung dapat memb
perlu dijelasin kalau `element.references` sebenernya narget element yang memiliki class `references` biar lebih jelas

```suggestion
Karena referensi tidak termasuk ke dalam paragraf di dalam artikel, kita harus membuat tampilan paragraf referensi tampak berbeda dengan paragraf artikel. Hal ini bertujuan agar pengunjung dapat membedakan paragraf berisi artikel dengan paragraf khusus referensi. Gunakan selector `element.references` untuk mengubah format teks yang ada pada suatu element yang memiliki class `references`.
```

2020-03-31 15:58 UTC, nargyanti commented
Mas, sudah saya update filenya

2020-03-31 22:46 UTC, mnindrazaka approved these changes
LGTM

2020-03-31 22:47 UTC, merged