merubah contoh permasalahan dan menambah contoh kasus serta merubah s…
wrideveloper/miniclass-web pull request #86
Opened 2020-04-11 16:12 UTC by zero0dayali

…truktur syllabus

2020-04-11 16:24 UTC, zero0dayali commented
mas aku mau tanya ,apa perlu aku tambahin tutorial cara buka fungsi nya misalkn pake chrome (buka file index.html) lalu klik kanan inspect elemen klik console ,

2020-04-11 23:35 UTC, mnindrazaka requested changes

2020-04-11 23:35 UTC, mnindrazaka commented on dasar/javascript/fungsi.md
> +4. Lalu kita lapor/return kan hasil dari penjumlahan nya.
ini kenapa jadi permasalahan kyk gini ? permasalahan disini maksudnya masalah apa yang kita hadapi sehingga kita menggunakan fungsi pada javascript

2020-04-11 23:35 UTC, mnindrazaka commented on dasar/javascript/fungsi.md
> +  var a = 8;
ini kenapa bahas cara menghitung volume ? penjelasan fungsinya mana, ikuti guideline yang sudah ada di issue atau repo guideline https://github.com/wrideveloper/miniclass-guideline

2020-04-11 23:36 UTC, mnindrazaka commented
> mas aku mau tanya ,apa perlu aku tambahin tutorial cara buka fungsi nya misalkn pake chrome (buka file index.html) lalu klik kanan inspect elemen klik console ,

gak perlu, contoh kasus yang dipake nanti yang berhubungan dengan manipulasi dom, jadi dilihat di browser aja udah kelihatan efek fungsinya

2020-04-11 23:37 UTC, mnindrazaka requested changes

2020-04-11 23:37 UTC, mnindrazaka commented on dasar/javascript/fungsi.md
> +  var a = 8;
ditambah lagi, kalau mau bikin contoh kasus, harus berhubungan dengan manipulasi dom, biar nyambung sama materi yang sebelumnya

2020-04-16 06:36 UTC, mnindrazaka requested changes

2020-04-16 06:36 UTC, mnindrazaka commented on dasar/javascript/fungsi.md
> +*Kita menggunakan variabel, lalu diisi dengan fungsi. Fungsi ini sebenarnya adalah fungsi anonim (anonymous function) atau fungsi tanpa nama.*
yang ini gak perlu

2020-04-16 06:36 UTC, mnindrazaka commented on dasar/javascript/fungsi.md
> +
yang ini juga gak perlu, ntar dijelasin di materi es6

2020-04-16 06:36 UTC, mnindrazaka commented on dasar/javascript/fungsi.md
> +  [.file contoh kasus](implementation/fungsi/fungsi.zip)
yang ini langkah - langkahnya juga perlu dibuat, ini bukan tugas, jadi perlu dikasih tau cara bikinnya, referensinya bisa lihat disini : 

https://github.com/wrideveloper/miniclass-web/blob/master/dasar/css/text-formatting.md

2020-04-16 06:36 UTC, mnindrazaka commented on dasar/javascript/fungsi.md
> +**console.log** = sebuah fungsi di javascript untuk menampilkan nilai yang sudah ditetntukan untuk ditampilkan kepada pengguna (di console)
kalau mau jelasin syntax kyk gini, lebih rapi kalau kamu kasih komentar di scriptnya, atau kalau emang mau dipisah, dikasih back tip aja, jangan di bold. Kemudian untuk `var`, `console.log()`, gak perlu dijelasin, udah dijelasin di materi lain

```suggestion
`function` merupakan keyword pada javascript untuk membuat fungsi baru  
`hitungLuasPersegiPanjang` merupakan nama fungsi yang akan dibuat 
`()` merupakan tempat meletakkan paramater fungsi
`{}` merupakan pembatas dari fungsi tersebut
```

2020-04-16 06:36 UTC, mnindrazaka commented on dasar/javascript/fungsi.md
> +5. Menggunakan return
yang ekspresi sama arrow function gak perlu, too much buat dijelasin sekarang

```suggestion
1. Menggunakan cara biasa;
2. Menggunakan parameter
3. Menggunakan return
```

2020-04-26 05:00 UTC, zero0dayali commented
contoh kasus ,itu maksudya bagaimana ya mas ,kalo di repo ini aku bermaksud buat contoh kasus yang seperti itu untuk dijadika sebagai latihan buat temen-temen jika sudah faham dengan baik struktur fungsi ,jadi aku buat kayak soal permasalahan kecil seperti itu , terus aku juga cantumin hasil codingan yang sudah selesai.

2020-04-26 09:53 UTC, mnindrazaka approved these changes
lgtm

2020-04-26 09:53 UTC, merged