feat(upload-file): add materi upload file
wrideveloper/miniclass-web pull request #88
Opened 2020-04-15 13:28 UTC by debbysa

2020-04-15 13:31 UTC, debbysa commented
berdasarkan issue #61

2020-04-18 12:48 UTC, mnindrazaka requested changes
Ada beberapa yang perlu diubah, aku udah bikin commit suggestion

Kemudian untuk point2 langkah pada point 3 dan 4, butuh dipecah jadi kecil2 dan dijelasin maksudnya dari setiap step, coba lihat referensinya disini, yang ini tulisannya udah rapi : 
https://github.com/wrideveloper/miniclass-web/blob/master/dasar/express-js/express-mysql.md

2020-04-18 12:48 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +Selain menerima data dari body raw (JSON, HTML, text biasa), sebuah web server juga dapat menerima file dari client. Misalnya apabila kita akan membuat sebuah web yang memiliki fitur upload seperti u
Disinggung soal `url encoded` dan `json`, biar nyambung dari materi sebelumnya

```suggestion
Selain menerima data dari body menggunakan format `url encoded` dan `json`, sebuah web server juga dapat menerima file dari client. Misalnya apabila kita akan membuat sebuah web yang memiliki fitur upload seperti upload foto profile.
```

2020-04-18 12:48 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +  ```
dari sisi client ga perlu dijelasin dulu sementara, ini dihapus dulu

```suggestion
```

2020-04-18 12:48 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +## 3. Penjelasan Detail Materi
judul point 3 ini gak harus `Penjelasan Detail Materi`, bisa disesuaikan dengan topik yang mau dibahas

```suggestion
## 3. Cara Parsing Form Data Menggunakan Middleware Multer
```

2020-04-18 12:48 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +    ```
penjelasan dari sisi client gak perlu dulu, soalnya bakal diseragamkan pake fetch api nanti
```suggestion
```

2020-04-18 12:48 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +    1. Buatlah folder untuk menyimpan file terlebih dahulu.
ini dijadiin sub point 3, jadi dia menjadi 3.1.

```suggestion
### 3.1. Buatlah folder untuk menyimpan file terlebih dahulu.
```

2020-04-18 16:26 UTC, debbysa commented on dasar/express-js/upload-file.md
> +    1. Buatlah folder untuk menyimpan file terlebih dahulu.
oke done

2020-04-18 16:29 UTC, debbysa commented on dasar/express-js/upload-file.md
> +    1. Buatlah folder untuk menyimpan file terlebih dahulu.
pagination nya jadi jelek tapi. ndak rapi kayak sebelumnya.
soalnya 3.1 kebaca text biasa, bukan kebaca penomoran

2020-04-25 11:34 UTC, mnindrazaka requested changes

2020-04-25 11:34 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +3.1 Buatlah folder untuk menyimpan file terlebih dahulu.
dikasih sub heading jangan lupa, terus dikasih penjelasan dikit

```suggestion
### 3.1 Membuat folder untuk menyimpan file
Langkah pertama untuk menerapkan multer pada express adalah dengan membuat folder untuk menyimpan file yang akan diunggah, misalnya folder `upload`
```

2020-04-25 11:34 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +```
ini gak perlu harusnya

2020-04-25 11:34 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +let upload = multer({ storage });
ada dua hal yang terjadi disini, menentukan lokasi sama nama file, jadi stepnya dipecah aja, source codemu banyak, penjelasanmu minim

2020-04-25 11:34 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +    res.send({ success: true });
maksud source code ini apa ? gak ada penjelasan

2020-04-25 11:35 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +3.1 Buatlah folder untuk menyimpan file terlebih dahulu.
jangan lupa, di sub point yang lain juga sama

2020-04-25 14:27 UTC, mnindrazaka requested changes

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +const storage = multer.diskStorage({
nama variablenya diganti aja biar gak bingung

```suggestion
const diskStorage = multer.diskStorage({
```

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +let upload = multer({ storage });
## 3.2. Membuat Konfigurasi Storage Multer

## 3.3. Mengkonfigurasi Destination Storage Multer

## 3.4. Mengkonfigurasi Filename Storage Multer

## 3.5. Menerapkan Middleware Multer 
langsung pake `multer({ storage: diskStorage }).single('fieldname')

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +    res.send({ success: true });
ini gak perlu middleware function lagi, langsung endpoint aja, misalnya cuma untuk menampilkan lokasi dan nama file yang sudah terupload

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +    res.send({ success: true });
langsung res.send aja, nama file dan pathnya

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +source code akhir contoh kasus :
```suggestion
Disini kita akan melanjutkan contoh kasus yang sudah dibuat pada materi sebelumnya. Kita akan menambahkan fitur untuk mengupload photo pada data contact yang sudah dibuat. Berikut langkah - langkah untuk melakukannya
```

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +4.2 Install `express` dan `multer`
bisa mulai dari sini, tapi gak perlu express

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +let upload = multer({ storage });
ini gajadi ya, langsung pake `multer({ storage }).single()`

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +});
ini jadi satu harusnya udah oke, karena di point 3 udah dijelasin dengan detail

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +```
langkah yang ini gak perlu

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +```
ini gak perlu, sebelumnya udah

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +  contacts[req.query.index] = { name: req.body.name, phone: req.body.phone };
ini juga gak usah

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +app.put("/contact/upload", upload.single("photo"), (req, res, next) => {
jangan lupa, ini sudah pake `multer({ storage: diskStorage }).single`

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +  next();
next() ini gak perlu

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +  console.log(file);
console.log gak perlu

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +  }
ini gak usah dulu

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +  contacts[req.query.index].photo = req.file.path;
`req.file.path` kalau belum ada nama filenya, ditambahkan nama filenya

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +```
ini juga gak usah

2020-04-25 14:27 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +  res.send({ success: true });
yang disini perlu disesuaikan sama step yang sudah diperbarui

2020-04-26 06:48 UTC, debbysa commented on dasar/express-js/upload-file.md
> +  contacts[req.query.index].photo = req.file.path;
aku jadinya tetep pake req.file.path

2020-04-26 07:41 UTC, debbysa reviewed
done mas

2020-04-26 11:13 UTC, debbysa reviewed
ini yang sudah sesuai review kemarin

2020-04-26 11:18 UTC, mnindrazaka requested changes

2020-04-26 11:18 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +### 3.2 Mendefinisikan Dependency `multer` dan `path`
ini gak ada langkah buat nginstall multernya ya ?

2020-04-26 11:18 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +  },
ini katanya mau dipecah ? kok langsung ditulis lengkap ?

2020-04-26 11:18 UTC, mnindrazaka commented on dasar/express-js/upload-file.md
> +  },
ini juga, kenapa udah ada filename ? katanya mau configure destination aja ?

2020-04-26 11:21 UTC, debbysa commented on dasar/express-js/upload-file.md
> +  },
kemarin ndak bilang gitu i. kan cuman let filename yang di hilangkan

2020-04-26 11:22 UTC, debbysa commented on dasar/express-js/upload-file.md
> +  },
katanya kalo di pecah pecah jadi rusak diskStorage nya. jdi tetep aku jadiin satu, cuman penjelasannya yang aku pecah

2020-04-26 11:23 UTC, debbysa commented on dasar/express-js/upload-file.md
> +### 3.2 Mendefinisikan Dependency `multer` dan `path`
wait aku tambahkan

2020-04-26 11:37 UTC, mnindrazaka approved these changes
lgtm

2020-04-26 11:37 UTC, merged