Event
wrideveloper/miniclass-web pull request #89
Opened 2020-04-18 04:02 UTC by fransiskalidya

mas, tolong direview

2020-04-18 05:22 UTC, ghost approved these changes

2020-04-18 22:44 UTC, mnindrazaka requested changes
Kyknya contoh kasusnya perlu diganti, soalnya di materi ini belum bisa pake fungsi atau dom manipulation. Jadi contoh kasusnya bisa dibuat lebih sederhana

2020-04-18 22:44 UTC, mnindrazaka commented on dasar/javascript/event.md
> +Normalnya, event dikombinasikan dengan fungsi dimana fungsi tidak akan dieksekusi sebelum event terjadi
semua penjelasan yang berkaitan dengan fungsi dihapus dulu ya, soalnya di materi ini, fungsi javascript itu belum dijelasin. Jadi jelasin event dlu baru fungsi, beda sama yang kamu dapat di miniclass.

```suggestion
```

Untuk materi fungsinya nanti dijelaskan sama @zero0dayali

2020-04-18 22:44 UTC, mnindrazaka commented on dasar/javascript/event.md
> +9. **onfocus**    : Event ketika kursor user terletak pada kolom text. Contoh penggunaan  **onblur** dan **onfocus** pada form inputan data
kalau mau jelasin syntax kyk gini, lebih rapi kalo pake tanda backtip (`)

```suggestion
1. `onclick`    : Event ketika user melakukan klik pada button 
2. `onkeypress` : Event ketika user menekan keyboard
3. `onchange`   : Event ketika nilai dari input form berubah 
4. `onload`     : Event ketika suatu elemen selesai dimuat
5. `onkeydown`  : Event ketika tombol keyboard ditekan atau dalam posisi down
6. `onkeyup`    : Event ketika tombol keyboard selesai ditekan atau dalam posisi up
7. `onsubmit`   : Event ketika suatu form akan mengirimkan data inputan 
8. `onblur`     : Event ketika kursor user terletak diluar kolom text 
9. `onfocus`    : Event ketika kursor user terletak pada kolom text. Contoh penggunaan  `onblur` dan `onfocus` pada form inputan data
```

2020-04-18 22:44 UTC, mnindrazaka commented on dasar/javascript/event.md
> +Pada div dengan class `app`, berisi 2 div dengan class `form` dan `biodata`. class `form` berisi kolom yang dapat disi dengan data dan button submit untuk menampilkan data. sedangkan class `biodata`
Penjelasan di tiap langkah2nya tolong ditaruh pas dibawah judulnya ya, jadi judul, penjelasan, baru scriptnya. Biar lebih rapi

2020-04-18 22:44 UTC, mnindrazaka commented on dasar/javascript/event.md
> +Deklarasikan variabel yang digunakan untuk mengambil elemen yang ada pada file html dengan selection `getElementById`.
kyknya gabisa pake `document.getElementById` dulu deh, soalnya belum bahas dom manipulation disini, ntar dibahas sama @nargyanti

2020-04-18 22:44 UTC, mnindrazaka commented on dasar/javascript/event.md
> +Buatlah fungsi yang akan dijalankan saat button di klik. Fungsi ini menampilkan alert yang berisi "hallo (nama yang diinput)" dan bertugas untuk memanggil fungsi selanjutnya, yaitu `addBio()`
yang ini juga, gabisa pake fungsi dulu

2020-04-18 22:44 UTC, mnindrazaka commented on dasar/javascript/event.md
> +```
yang ini juga

2020-04-18 22:44 UTC, mnindrazaka commented on dasar/javascript/event.md
> +
ini juga gabisa

2020-04-18 23:33 UTC, fransiskalidya commented on dasar/javascript/event.md
> +Pada div dengan class `app`, berisi 2 div dengan class `form` dan `biodata`. class `form` berisi kolom yang dapat disi dengan data dan button submit untuk menampilkan data. sedangkan class `biodata`
Oke, siap mas

2020-04-26 10:06 UTC, mnindrazaka approved these changes
lgtm

2020-04-26 10:06 UTC, merged