Melakukan perubahan pada struktur pengenalan javascript
wrideveloper/miniclass-web pull request #96
Opened 2020-04-26 14:28 UTC by widiarsaf

2020-04-26 14:34 UTC, widiarsaf commented
Mas Aka, yang poin 3.2 interaksi yang dapat dilakukan javascript belum

2020-04-26 20:21 UTC, mnindrazaka requested changes

2020-04-26 20:21 UTC, mnindrazaka commented on dasar/javascript/pengenalan-javascript.md
> +### 3.2 Interaksi Yang Dapat Dilakukan Javascript
Point yang ini udah gak perlu, soalnya sudah kamu jelasin di point `2. Penjelasan Javascript`

```suggestion
```

2020-04-26 20:21 UTC, mnindrazaka commented on dasar/javascript/pengenalan-javascript.md
> +            onclick="alert('Oops Your Connection In Troble')">submit</button>
Ga perlu jelasin onclick dulu ya, soalnya itu masuk materi event punya si @fransiskalidya 
```suggestion
>submit</button>
```

2020-04-26 20:21 UTC, mnindrazaka commented on dasar/javascript/pengenalan-javascript.md
> +![pengenalan-javascript](alert(2).jpg)
yang ini juga jangan lupa dihapus, soalnya kita gak pake contoh `onclick`, soalnya masuk materi event

```suggestion
```

2020-04-27 06:51 UTC, mnindrazaka approved these changes
lgtm

2020-04-27 06:51 UTC, merged